default_font = "src/fonts/no_continue.ttf"
background_color = (222, 222, 222)
outline_color = (0, 0, 0) 
filling_color = (255, 255, 255)
score_color = (74, 74, 74)
lobby_bg_color = background_color
lobby_color = score_color
lobby_fontsize = 40
summary_bg_color = background_color
summary_color = score_color
summary_fontsize = 30